using AutoMapper;
using e_maktab.DataLayer.AutoGenerated;

namespace e_maktab.BizLogicLayer.Services.Admin.User.Mapper;

public class UserMapper : Profile
{
    public UserMapper()
    {
        CreateMap<CreateUserDto, User>()
         .ForMember(s => s.DateOfCreated, p => p.MapFrom(s => DateTime.UtcNow))
         .ForMember(s => s.StateId, s => s.MapFrom(s => 1));


    }
}
