using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace e_maktab.DataLayer.AutoGenerated;

[Table("class")]
public partial class Class
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("organization_id")]
    public int? OrganizationId { get; set; }

    [Column("language_id")]
    public int? LanguageId { get; set; }

    [Column("teacher_id")]
    public int? TeacherId { get; set; }

    [Column("class_type_id")]
    public int? ClassTypeId { get; set; }

    [Column("state_id")]
    public int StateId { get; set; }

    [Column("dagree")]
    public int Dagree { get; set; }

    [Column("date_of_created", TypeName = "timestamp without time zone")]
    public DateTime DateOfCreated { get; set; }

    [Column("date_of_modified", TypeName = "timestamp without time zone")]
    public DateTime? DateOfModified { get; set; }

    [ForeignKey("ClassTypeId")]
    [InverseProperty("Classes")]
    public virtual ClassType? ClassType { get; set; }

    [ForeignKey("LanguageId")]
    [InverseProperty("Classes")]
    public virtual EnumLanguage? Language { get; set; }

    [ForeignKey("OrganizationId")]
    [InverseProperty("Classes")]
    public virtual Organization? Organization { get; set; }

    [ForeignKey("StateId")]
    [InverseProperty("Classes")]
    public virtual EnumState State { get; set; } = null!;

    [ForeignKey("TeacherId")]
    [InverseProperty("Classes")]
    public virtual User? Teacher { get; set; }
}
