using e_maktab.DataLayer.AutoGenerated;
using e_maktab.DataLayer.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace e_maktab.DataLayer.Repositories;

public interface IUserRepository:IGenericRepository<User>
{

}
